language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head

notifications:
  disabled: true

script:
  - bundle exec rake spec

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - sudo apt-get update
  - echo $(uname -r)
  - sudo apt-get install build-essential gcc automake linux-headers-$(uname -r) -yqq
